In [1]:
print("hello")

hello

**data reading**

In [1]:
import pandas as pd
import numpy as np

In [2]:
m_data = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/merged_data.csv')
m_data

,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
0,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...
495,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
496,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
497,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
498,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
499,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

In [6]:
m_data.head(8)

,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
0,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
5,2024-07-07,West,Laptop,Electronics,New,8,1480,11721.60,2,NaN
6,2024-01-21,East,Mouse,Accessories,Returning,6,137,600.06,1,high
7,2024-04-12,West,Phone,Accessories,Returning,5,1117,4132.90,2,very high

In [7]:
m_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             500 non-null    str
 1   region           500 non-null    str
 2   product          500 non-null    str
 3   category         500 non-null    str
 4   customer_type    500 non-null    str
 5   quantity         500 non-null    int64
 6   price            500 non-null    int64
 7   sales            500 non-null    float64
 8   customer_rating  500 non-null    int64
 9   sales_category   375 non-null    str
dtypes: float64(1), int64(3), str(6)
memory usage: 39.2 KB

In [8]:
m_data.describe()

         quantity        price         sales  customer_rating
count  500.000000   500.000000    500.000000       500.000000
mean     4.968000   768.158000   3333.059560         2.480000
std      2.569081   404.010497   2693.185995         1.118975
min      1.000000    50.000000     67.320000         1.000000
25%      3.000000   432.750000   1120.867500         1.000000
50%      5.000000   742.000000   2582.805000         2.500000
75%      7.000000  1094.500000   4998.030000         3.000000
max      9.000000  1499.000000  12700.800000         4.000000

In [13]:
m_data.columns

Index(['date', 'region', 'product', 'category', 'customer_type', 'quantity',
       'price', 'sales', 'customer_rating', 'sales_category'],
      dtype='str')

In [14]:
m_data.rename(columns={"customer_type":"Customer_Type"}, inplace=False)

,date,region,product,category,Customer_Type,quantity,price,sales,customer_rating,sales_category
0,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...
495,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
496,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
497,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
498,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
499,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

**data cleaning task**

In [15]:
m_data = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/merged_data.csv')
m_data

,date,region,product,category,customer_type,quantity,price,sales,customer_rating,sales_category
0,2024-04-12,East,Laptop,Electronics,Returning,8,590,4295.20,1,very high
1,2024-12-14,South,Monitor,Accessories,Returning,2,262,429.68,1,medium
2,2024-09-27,North,Phone,Accessories,New,5,512,2329.60,2,very high
3,2024-04-16,West,Mouse,Electronics,Returning,1,485,441.35,1,medium
4,2024-03-12,West,Phone,Electronics,Returning,7,332,1812.72,4,very high
...,...,...,...,...,...,...,...,...,...,...
495,2024-11-20,South,Mouse,Accessories,Returning,6,314,1450.68,3,very high
496,2024-01-04,North,Phone,Accessories,Returning,9,369,2557.17,4,very high
497,2024-01-16,South,Keyboard,Electronics,Returning,6,722,3725.52,4,very high
498,2024-10-06,North,Phone,Accessories,Returning,2,1449,2550.24,1,very high
499,2024-12-01,North,Monitor,Electronics,New,2,869,1581.58,1,very high

In [23]:
m_data["date"]= pd.to_datetime(m_data["date"])

In [17]:
m_data.isnull().sum()

date                 0
region               0
product              0
category             0
customer_type        0
quantity             0
price                0
sales                0
customer_rating      0
sales_category     125
dtype: int64

In [40]:
m_data["sales_category"]=(m_data["sales_category"].fillna("Unknown"))
print(m_data["sales_category"])

0      very high
1         medium
2      very high
3         medium
4      very high
         ...
495    very high
496    very high
497    very high
498    very high
499    very high
Name: sales_category, Length: 500, dtype: str

In [27]:
m_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [32]:
m_data.duplicated().sum()

np.int64(0)

In [33]:
m_data.dtypes

date               datetime64[us]
region                        str
product                       str
category                      str
customer_type                 str
quantity                    int64
price                       int64
sales                     float64
customer_rating             int64
sales_category                str
dtype: object

In [43]:
m_data["quantity"]= m_data["quantity"].astype(int)
print(m_data["quantity"])

0      8
1      2
2      5
3      1
4      7
      ..
495    6
496    9
497    6
498    2
499    2
Name: quantity, Length: 500, dtype: int64

In [42]:
m_data["price"]= m_data["price"].astype(float)
print(m_data["price"])

0       590.0
1       262.0
2       512.0
3       485.0
4       332.0
        ...
495     314.0
496     369.0
497     722.0
498    1449.0
499     869.0
Name: price, Length: 500, dtype: float64

In [41]:
m_data["region"] = m_data["region"].str.strip().str.title()
print(m_data["region"])

0       East
1      South
2      North
3       West
4       West
       ...
495    South
496    North
497    South
498    North
499    North
Name: region, Length: 500, dtype: str

**data analysis task**

In [2]:
import pandas as pd
m_data = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/merged_data.csv')
# Total sales per region
total_sales_region = m_data.groupby('region')['sales'].sum()

# Region with the highest sales
highest_sales_region = total_sales_region.idxmax()
highest_sales_amount = total_sales_region.max()

print(total_sales_region)
print(f"Highest sales region: {highest_sales_region} with sales {highest_sales_amount}")

region
East     422023.71
North    509052.69
South    362158.72
West     373294.66
Name: sales, dtype: float64
Highest sales region: North with sales 509052.69

In [9]:
m_data.groupby("customer_type")['customer_rating'].mean()

customer_type
New          2.472803
Returning    2.486590
Name: customer_rating, dtype: float64

In [11]:
m_data.groupby("product")["quantity"].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [13]:
#convert datetime
m_data['date'] = pd.to_datetime(m_data['date'])
print(m_data['date'])

0     2024-04-12
1     2024-12-14
2     2024-09-27
3     2024-04-16
4     2024-03-12
         ...
495   2024-11-20
496   2024-01-04
497   2024-01-16
498   2024-10-06
499   2024-12-01
Name: date, Length: 500, dtype: datetime64[us]

In [ ]:
#profitable product
m_data.groupby('product')['sales'].sum().max()

np.float64(317281.14)

In [20]:
m_data.groupby('product')['sales'].sum().max()

np.float64(317281.14)

In [21]:
m_data.groupby('customer_type')['quantity'].mean()

customer_type
New          4.937238
Returning    4.996169
Name: quantity, dtype: float64