In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [10]:
import pandas as pd
data = {
    "name": ["ali" , "hasan" , "saad"],
    "age": [21 , 23 , 34]
}

df = pd.DataFrame(data)
print(df)

    name  age
0    ali   21
1  hasan   23
2   saad   34

In [5]:
import pandas as pd
                                                  #a cmplt dataframe
d = {"a": [1,2,3,4] , "s": [2,3,4,5]}

df = pd.DataFrame(d)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   a  s
0  1  2
1  2  3
2  3  4
3  4  5

In [ ]:
import pandas as pd
data = {"a":[1,2,3,4] ,"s":[3,4,5,6] , "d":[3,4,5,7]}                     #dictionary se dataframe bnaya

df = pd.DataFrame(data , index = [1,2,3,4])

print(df)

   a  s  d
1  1  3  3
2  2  4  4
3  3  5  5
4  4  6  7

In [9]:
import pandas as pd
l = {"s": pd.Series([1,2,3,4]), "r": pd.Series([2,3,4,5])}              #2 SERIES SE DATAFRAME CREATE KRNA
var = pd.DataFrame(l)
print(var)
print(type(var))

   s  r
0  1  2
1  2  3
2  3  4
3  4  5
<class 'pandas.DataFrame'>

arthimetic operations

In [18]:
import pandas as pd

var = pd.DataFrame({"s":[1,2,3,4,5] , "d":[6,7,8,9,10]})
print(var)
print(type(var))

   s   d
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10
<class 'pandas.DataFrame'>

In [19]:
var["C"] = var["s"]+ var["d"]
var

   s   d   C
0  1   6   7
1  2   7   9
2  3   8  11
3  4   9  13
4  5  10  15

In [ ]:
var["c"] = var["s"] - var["d"]                                             #same esy hi baki opration krny
var

   s   d   C  c
0  1   6   7 -5
1  2   7   9 -5
2  3   8  11 -5
3  4   9  13 -5
4  5  10  15 -5

In [34]:
var = pd.DataFrame({"A":[20,21,22,23,24,25] ,"B": [25,26,27,28,29,30]})
print(type(var))
print(var)

<class 'pandas.DataFrame'>
    A   B
0  20  25
1  21  26
2  22  27
3  23  28
4  24  29
5  25  30

In [ ]:
var ["python"] = var ["A"] <= 22                                       #greater less method
var

    A   B  python
0  20  25    True
1  21  26    True
2  22  27    True
3  23  28   False
4  24  29   False
5  25  30   False

In [39]:
var ["python_1"] = var["A"] >= 27
var

    A   B  python  python_1
0  20  25    True     False
1  21  26    True     False
2  22  27    True     False
3  23  28   False     False
4  24  29   False     False
5  25  30   False     False

INSERT DATA

In [52]:
import pandas as pd

var = pd.DataFrame({"sugar": [8,7,6,5,4,9] , "salt": [4,5,6,7,2,1]})

print(type(var))
var

<class 'pandas.DataFrame'>

   sugar  salt
0      8     4
1      7     5
2      6     6
3      5     7
4      4     2
5      9     1

In [ ]:
var.insert(2,"new set" , var["sugar"])        #use insert and 3 parameters index,new column name,kya insert krna
var

   sugar  salt  new set
0      8     4        8
1      7     5        7
2      6     6        6
3      5     7        5
4      4     2        4
5      9     1        9

In [50]:
var.insert(3,"new set2" , [1,2,3,4,5,6])
var

   sugar  salt  new set  new set2
0      8     4        8         1
1      7     5        7         2
2      6     6        6         3
3      5     7        5         4
4      4     2        4         5
5      9     1        9         6

In [16]:
import pandas as pd

data = pd.DataFrame({"name": ["ali" , "ahmad" , "ayan"],
                     "age": [21,22,23],
                     "city": ["lahore" , "gujranwala" , "islamabad"]
                     })
df = pd.DataFrame(data)
print(type(data))
data

<class 'pandas.DataFrame'>

    name  age        city
0    ali   21      lahore
1  ahmad   22  gujranwala
2   ayan   23   islamabad

In [ ]:
data.insert(1,"marks", [85,90,88])                                   #insert column specific position
data

    name  marks  age        city
0    ali     85   21      lahore
1  ahmad     90   22  gujranwala
2   ayan     88   23   islamabad

In [20]:
df.loc[len(df)] = ["sana" , 54, "marque"]                     #row insert method
df

    name  age        city
0    ali   21      lahore
1  ahmad   22  gujranwala
2   ayan   23   islamabad
3   sana   54      marque

In [24]:
import pandas as pd

data = ({"name": ["ali" , "ahmad","ayan","sana","zara"],
        "marks": [45,54,56,67,39],
        "city": ["lhr","grw","isl","lhr","grw"]
        })
df = pd.DataFrame(data)
df

    name  marks city
0    ali     45  lhr
1  ahmad     54  grw
2   ayan     56  isl
3   sana     67  lhr
4   zara     39  grw

In [ ]:
df["marks"]
                                            #column filter out kiya

0    45
1    54
2    56
3    67
4    39
Name: marks, dtype: int64

In [ ]:
df.iloc[3]                                                #row pick ki

bonus      23
name     sana
marks      67
city      lhr
Name: 3, dtype: object

In [ ]:
df.insert(0,"sixe",[12,34,56,23,65] )                      #new column add kiya
df

   sixe  bonus   name  marks city
0    12     12    ali     45  lhr
1    34     34  ahmad     54  grw
2    56     56   ayan     56  isl
3    23     23   sana     67  lhr
4    65     65   zara     39  grw

In [47]:
new_result = df["marks"] >55
print(new_result)

0    False
1    False
2     True
3     True
4    False
Name: marks, dtype: bool

In [48]:
df.shape

(5, 5)

In [50]:
df.sort_values("marks", ascending=True)

   sixe  bonus   name  marks city
4    65     65   zara     39  grw
0    12     12    ali     45  lhr
1    34     34  ahmad     54  grw
2    56     56   ayan     56  isl
3    23     23   sana     67  lhr

limited amount of data

In [69]:
import pandas as pd
var = pd.DataFrame({"A":[20,21,22,23,24,25] ,"B": [25,26,27,28,29,30]})
print(type(var))
print(var)

<class 'pandas.DataFrame'>
    A   B
0  20  25
1  21  26
2  22  27
3  23  28
4  24  29
5  25  30

In [70]:
var["panda"]= var["B"][:4]                                  #limited data copy kiya baki me nan aya
var

    A   B  panda
0  20  25   25.0
1  21  26   26.0
2  22  27   27.0
3  23  28   28.0
4  24  29    NaN
5  25  30    NaN

**delete**

In [71]:
var1 = var.pop("B")                          #ye bta rha kya delete kiya pop kiya
var1

0    25
1    26
2    27
3    28
4    29
5    30
Name: B, dtype: int64

In [ ]:
var                                              #ab ye likhny se baki data show hwa

    A  panda
0  20   25.0
1  21   26.0
2  22   27.0
3  23   28.0
4  24    NaN
5  25    NaN

In [72]:
del var["A"]
var

   panda
0   25.0
1   26.0
2   27.0
3   28.0
4    NaN
5    NaN

In [23]:
import pandas as pd

data = ({"name":["ali","ahmad","sara","hasan"], "marks":[85,95,99,97]})
df = pd.DataFrame(data)
df

    name  marks
0    ali     85
1  ahmad     95
2   sara     99
3  hasan     97

In [24]:
df.insert(1,"grade",["a","b","c","d"])
df

    name grade  marks
0    ali     a     85
1  ahmad     b     95
2   sara     c     99
3  hasan     d     97