**csv files**

In [ ]:
import pandas as pd

d = {"a": [1,2,3,4,5,6], "s":[2,3,4,5,6,7], "d":[3,4,5,6,7,8]}
df = pd.DataFrame(d)
print(df)
                                                         #khud create ki csv file
df.to_csv("test2_new.csv",index=False, header=[1,2,3])

ModuleNotFoundError: No module named 'pandas'

**csv file read**

In [6]:
import pandas as pd

df = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [7]:
df = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv',nrows=3)
df                                                                              #row get

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0

In [8]:
df1 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv', usecols=[2])
df1                                                                     #column get krna with index

    Pulse
0     110
1     117
2     103
3     109
4     117
5     102
6     110
7     104
8     109
9      98
10    103
11    100
12    100
13    106
14    104
15     98
16     98
17    100
18     90
19    103
20     97
21    108
22    100
23    130
24    105
25    102
26    100
27     92
28    103
29    100
30    102
31     92

In [9]:
df2= pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv',skiprows=[2])
df2

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/03'    103       135     340.0
2         45  '2020/12/04'    109       175     282.4
3         45  '2020/12/05'    117       148     406.0
4         60  '2020/12/06'    102       127     300.0
5         60  '2020/12/07'    110       136     374.0
6        450  '2020/12/08'    104       134     253.3
7         30  '2020/12/09'    109       133     195.1
8         60  '2020/12/10'     98       124     269.0
9         60  '2020/12/11'    103       147     329.3
10        60  '2020/12/12'    100       120     250.7
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/13'    106       128     345.3
13        60  '2020/12/14'    104       132     379.3
14        60  '2020/12/15'     98       123     275.0
15        60  '2020/12/16'     98       120     215.2
16        60  '2020/12/17'    100       120     300.0
17        45  '2020/12/18'     90       112       NaN
18        60  '2020/12/19'    103       123     323.0
19        45  '2020/12/20'     97       125     243.0
20        60  '2020/12/21'    108       131     364.2
21        45           NaN    100       119     282.0
22        60  '2020/12/23'    130       101     300.0
23        45  '2020/12/24'    105       132     246.0
24        60  '2020/12/25'    102       126     334.5
25        60      20201226    100       120     250.0
26        60  '2020/12/27'     92       118     241.0
27        60  '2020/12/28'    103       132       NaN
28        60  '2020/12/29'    100       132     280.0
29        60  '2020/12/30'    102       129     380.3
30        60  '2020/12/31'     92       115     243.0

In [19]:
df3 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv',index_col=[2])
df3

       Duration          Date  Maxpulse  Calories
Pulse
110          60  '2020/12/01'       130     409.1
117          60  '2020/12/02'       145     479.0
103          60  '2020/12/03'       135     340.0
109          45  '2020/12/04'       175     282.4
117          45  '2020/12/05'       148     406.0
102          60  '2020/12/06'       127     300.0
110          60  '2020/12/07'       136     374.0
104         450  '2020/12/08'       134     253.3
109          30  '2020/12/09'       133     195.1
98           60  '2020/12/10'       124     269.0
103          60  '2020/12/11'       147     329.3
100          60  '2020/12/12'       120     250.7
100          60  '2020/12/12'       120     250.7
106          60  '2020/12/13'       128     345.3
104          60  '2020/12/14'       132     379.3
98           60  '2020/12/15'       123     275.0
98           60  '2020/12/16'       120     215.2
100          60  '2020/12/17'       120     300.0
90           45  '2020/12/18'       112       NaN
103          60  '2020/12/19'       123     323.0
97           45  '2020/12/20'       125     243.0
108          60  '2020/12/21'       131     364.2
100          45           NaN       119     282.0
130          60  '2020/12/23'       101     300.0
105          45  '2020/12/24'       132     246.0
102          60  '2020/12/25'       126     334.5
100          60      20201226       120     250.0
92           60  '2020/12/27'       118     241.0
103          60  '2020/12/28'       132       NaN
100          60  '2020/12/29'       132     280.0
102          60  '2020/12/30'       129     380.3
92           60  '2020/12/31'       115     243.0

In [22]:
df4 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv',header=22)
df4

   60  '2020/12/21'  108  131  364.2
0  45           NaN  100  119  282.0
1  60  '2020/12/23'  130  101  300.0
2  45  '2020/12/24'  105  132  246.0
3  60  '2020/12/25'  102  126  334.5
4  60      20201226  100  120  250.0
5  60  '2020/12/27'   92  118  241.0
6  60  '2020/12/28'  103  132    NaN
7  60  '2020/12/29'  100  132  280.0
8  60  '2020/12/30'  102  129  380.3
9  60  '2020/12/31'   92  115  243.0

In [3]:
df5 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv', dtype={"Maxpulse":float})
df5                                                         #datatype change

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110     130.0     409.1
1         60  '2020/12/02'    117     145.0     479.0
2         60  '2020/12/03'    103     135.0     340.0
3         45  '2020/12/04'    109     175.0     282.4
4         45  '2020/12/05'    117     148.0     406.0
5         60  '2020/12/06'    102     127.0     300.0
6         60  '2020/12/07'    110     136.0     374.0
7        450  '2020/12/08'    104     134.0     253.3
8         30  '2020/12/09'    109     133.0     195.1
9         60  '2020/12/10'     98     124.0     269.0
10        60  '2020/12/11'    103     147.0     329.3
11        60  '2020/12/12'    100     120.0     250.7
12        60  '2020/12/12'    100     120.0     250.7
13        60  '2020/12/13'    106     128.0     345.3
14        60  '2020/12/14'    104     132.0     379.3
15        60  '2020/12/15'     98     123.0     275.0
16        60  '2020/12/16'     98     120.0     215.2
17        60  '2020/12/17'    100     120.0     300.0
18        45  '2020/12/18'     90     112.0       NaN
19        60  '2020/12/19'    103     123.0     323.0
20        45  '2020/12/20'     97     125.0     243.0
21        60  '2020/12/21'    108     131.0     364.2
22        45           NaN    100     119.0     282.0
23        60  '2020/12/23'    130     101.0     300.0
24        45  '2020/12/24'    105     132.0     246.0
25        60  '2020/12/25'    102     126.0     334.5
26        60      20201226    100     120.0     250.0
27        60  '2020/12/27'     92     118.0     241.0
28        60  '2020/12/28'    103     132.0       NaN
29        60  '2020/12/29'    100     132.0     280.0
30        60  '2020/12/30'    102     129.0     380.3
31        60  '2020/12/31'     92     115.0     243.0

In [10]:
import pandas as pd
df6 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv')
df6.sort_index(axis=0,ascending=False)                             #axis 0 mtlb ascending or 1 axis mtlb descen

    Duration          Date  Pulse  Maxpulse  Calories
31        60  '2020/12/31'     92       115     243.0
30        60  '2020/12/30'    102       129     380.3
29        60  '2020/12/29'    100       132     280.0
28        60  '2020/12/28'    103       132       NaN
27        60  '2020/12/27'     92       118     241.0
26        60      20201226    100       120     250.0
25        60  '2020/12/25'    102       126     334.5
24        45  '2020/12/24'    105       132     246.0
23        60  '2020/12/23'    130       101     300.0
22        45           NaN    100       119     282.0
21        60  '2020/12/21'    108       131     364.2
20        45  '2020/12/20'     97       125     243.0
19        60  '2020/12/19'    103       123     323.0
18        45  '2020/12/18'     90       112       NaN
17        60  '2020/12/17'    100       120     300.0
16        60  '2020/12/16'     98       120     215.2
15        60  '2020/12/15'     98       123     275.0
14        60  '2020/12/14'    104       132     379.3
13        60  '2020/12/13'    106       128     345.3
12        60  '2020/12/12'    100       120     250.7
11        60  '2020/12/12'    100       120     250.7
10        60  '2020/12/11'    103       147     329.3
9         60  '2020/12/10'     98       124     269.0
8         30  '2020/12/09'    109       133     195.1
7        450  '2020/12/08'    104       134     253.3
6         60  '2020/12/07'    110       136     374.0
5         60  '2020/12/06'    102       127     300.0
4         45  '2020/12/05'    117       148     406.0
3         45  '2020/12/04'    109       175     282.4
2         60  '2020/12/03'    103       135     340.0
1         60  '2020/12/02'    117       145     479.0
0         60  '2020/12/01'    110       130     409.1

In [ ]:
import pandas as pd
df7 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv')
df7.loc[[4,10],[ "Maxpulse" ,	"Calories"]]                                              #koi b row or column get

    Maxpulse  Calories
4        148     406.0
10       147     329.3

In [14]:
import pandas as pd
df8 = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/data.csv')
df8.loc[[2,3],:]

   Duration          Date  Pulse  Maxpulse  Calories
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4

**fillna and dropna method**