In [2]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","Ahmed"],
    "Age": [22,25,23]
}

df = pd.DataFrame(data)
df

    Name  Age
0    Ali   22
1   Sara   25
2  Ahmed   23

In [7]:
import numpy as np
import pandas as pd

data = np.random.randint(1,100,(10,20))

df = pd.DataFrame(data)

print(df)

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0  28  48  86  63  66  88  14  17  94  90  23  20  59  18  42  25  93   1  45
1  77  38  53  91   5  25  97   6  38  70   2  50  50  68  90  43  60  84  91
2  12  55  52   3  43  23  42  69  96  54  80  36  57  21  90  50  39  97  71
3  57  88  29   5  75  43   6  57  85  44  41  97  18  92  51  32  22  24  96
4  71  85   7   7  96  76  22  77  63   3   5  34  84  77  65  43  57  59   3
5  78  65  85  81  60  82  14  49  92  24   5  81  20  31  23   3  36  79  51
6  85  86  62  33  95  91  69  26  78  39  65  96  88  75  80  52  99  38  38
7  95  79  41  98  12  17  61  12  12  32  71   9  78  78  42  97  66  34  18
8  69  62  72  86   2  14  73  59  77  43  89  46  51  28  94  24  78  25  16
9  45  76  19  11  18  84  37  18  18  34  70  38  56  79  28  13  56  49  89

   19
0  60
1  92
2  91
3  92
4  38
5  63
6  97
7  29
8  78
9  49

In [3]:
import pandas as pd
import numpy as np
# Creating Series from different sources
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
s3 = pd.Series({'a': 10, 'b': 20, 'c': 30})
s4 = pd.Series(np.random.randn(5))

# Series attributes
print(s2.index)
print(s2.values)
print(s2.dtype)

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
[1 2 3 4 5]
int64

In [24]:
data = {
    "name": ["ali" , "hasan" , "saad"],
    "age": [21 , 23 , 34]
}

df = pd.DataFrame(data)
print(df)

print(df.head(1))

    name  age
0    ali   21
1  hasan   23
2   saad   34
  name  age
0  ali   21

In [34]:
import pandas as pd
data = {
    "students": ["ali" , "ahmad" , "saad"],
    "roll no": [23,43,12],
    "subject": ["urdu" , "english" , "biology"]
}
df = pd.DataFrame(data)
print(df)
print(df.tail(2))
print(df.shape)
df.columns

  students  roll no  subject
0      ali       23     urdu
1    ahmad       43  english
2     saad       12  biology
  students  roll no  subject
1    ahmad       43  english
2     saad       12  biology
(3, 3)

Index(['students', 'roll no', 'subject'], dtype='str')

In [35]:
#column access krna
df["students"]

0      ali
1    ahmad
2     saad
Name: students, dtype: str

In [2]:
import pandas as pd

df= pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/weather.csv')
df

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [15]:
df = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/generic-food.csv')
df
df.info()                                                    #column name type null sb btata

<class 'pandas.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FOOD NAME        906 non-null    str
 1   SCIENTIFIC NAME  648 non-null    str
 2   GROUP            903 non-null    str
 3   SUB GROUP        903 non-null    str
dtypes: str(4)
memory usage: 28.4 KB

In [ ]:
print(df.describe())                                     #only numbers

       FOOD NAME  SCIENTIFIC NAME          GROUP SUB GROUP
count        906              648            903       903
unique       906              639             24       123
top     Angelica  Capsicum annuum  Aquatic foods    Fishes
freq           1                6            166       111

In [ ]:
print(df.loc[0:2])                          #range di exact

       FOOD NAME                 SCIENTIFIC NAME             GROUP SUB GROUP
0       Angelica                Angelica keiskei  Herbs and Spices     Herbs
1  Savoy cabbage  Brassica oleracea var. sabauda        Vegetables  Cabbages
2  Silver linden                  Tilia argentea  Herbs and Spices     Herbs

In [9]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
901    False
902    False
903    False
904    False
905    False
Length: 906, dtype: bool

In [10]:
print(df.drop_duplicates())

           FOOD NAME                                    SCIENTIFIC NAME  \
0           Angelica                                   Angelica keiskei
1      Savoy cabbage                     Brassica oleracea var. sabauda
2      Silver linden                                     Tilia argentea
3               Kiwi                                Actinidia chinensis
4     Allium (Onion)                                             Allium
..               ...                                                ...
901    White cabbage  Brassica oleracea L. var. capitata L. f. alba DC.
902  Romaine lettuce                  Lactuca sativa L. var. longifolia
903        dumplings                                                NaN
904           muesli                                                NaN
905             milk                                                NaN

                GROUP                SUB GROUP
0    Herbs and Spices                    Herbs
1          Vegetables                 Cabbages
2    Herbs and Spices                    Herbs
3              Fruits          Tropical fruits
4          Vegetables  Onion-family vegetables
..                ...                      ...
901        Vegetables                 Cabbages
902        Vegetables          Leaf vegetables
903               NaN                      NaN
904               NaN                      NaN
905               NaN                      NaN

[906 rows x 4 columns]

In [ ]:
print(df.iloc[1])

FOOD NAME                           Savoy cabbage
SCIENTIFIC NAME    Brassica oleracea var. sabauda
GROUP                                  Vegetables
SUB GROUP                                Cabbages
Name: 1, dtype: str

In [12]:
print(df.value_counts())                                      #count unique values

FOOD NAME         SCIENTIFIC NAME                                    GROUP             SUB GROUP
Angelica          Angelica keiskei                                   Herbs and Spices  Herbs                      1
Savoy cabbage     Brassica oleracea var. sabauda                     Vegetables        Cabbages                   1
Silver linden     Tilia argentea                                     Herbs and Spices  Herbs                      1
Kiwi              Actinidia chinensis                                Fruits            Tropical fruits            1
Allium (Onion)    Allium                                             Vegetables        Onion-family vegetables    1
                                                                                                                 ..
Saskatoon berry   Amelanchier alnifolia                              Fruits            Berries                    1
Nanking cherry    Prunus tomentosa                                   Fruits            Berries                    1
Japanese pumpkin  Cucurbita maxima                                   Gourds            Gourds                     1
White cabbage     Brassica oleracea L. var. capitata L. f. alba DC.  Vegetables        Cabbages                   1
Romaine lettuce   Lactuca sativa L. var. longifolia                  Vegetables        Leaf vegetables            1
Name: count, Length: 648, dtype: int64

In [14]:
df.ffill()

,FOOD NAME,SCIENTIFIC NAME,GROUP,SUB GROUP
0,Angelica,Angelica keiskei,Herbs and Spices,Herbs
1,Savoy cabbage,Brassica oleracea var. sabauda,Vegetables,Cabbages
2,Silver linden,Tilia argentea,Herbs and Spices,Herbs
3,Kiwi,Actinidia chinensis,Fruits,Tropical fruits
4,Allium (Onion),Allium,Vegetables,Onion-family vegetables
...,...,...,...,...
901,White cabbage,Brassica oleracea L. var. capitata L. f. alba DC.,Vegetables,Cabbages
902,Romaine lettuce,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables
903,dumplings,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables
904,muesli,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables
905,milk,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables

In [17]:
df.fillna(0)

,FOOD NAME,SCIENTIFIC NAME,GROUP,SUB GROUP
0,Angelica,Angelica keiskei,Herbs and Spices,Herbs
1,Savoy cabbage,Brassica oleracea var. sabauda,Vegetables,Cabbages
2,Silver linden,Tilia argentea,Herbs and Spices,Herbs
3,Kiwi,Actinidia chinensis,Fruits,Tropical fruits
4,Allium (Onion),Allium,Vegetables,Onion-family vegetables
...,...,...,...,...
901,White cabbage,Brassica oleracea L. var. capitata L. f. alba DC.,Vegetables,Cabbages
902,Romaine lettuce,Lactuca sativa L. var. longifolia,Vegetables,Leaf vegetables
903,dumplings,0,0,0
904,muesli,0,0,0
905,milk,0,0,0

In [21]:
print(df.isnull().sum())

FOOD NAME            0
SCIENTIFIC NAME    258
GROUP                3
SUB GROUP            3
dtype: int64

In [8]:
import pandas as pd
df = pd.read_csv('c:/Users/aqib farooq/Downloads/python daily tasks/generic-food.csv')
print(df.loc[2])

FOOD NAME             Silver linden
SCIENTIFIC NAME      Tilia argentea
GROUP              Herbs and Spices
SUB GROUP                     Herbs
Name: 2, dtype: str

In [9]:
print(sorted(df['FOOD NAME'].unique()))

['Abalone', 'Abiyuch', 'Acerola', 'Acorn', 'Adobo', 'Adzuki bean', 'Agar', 'Agave', 'Akutaq', 'Alaska blackfish', 'Alaska blueberry', 'Alaska pollock', 'Alaska wild rhubarb', 'Albacore tuna', 'Alcoholic beverages', 'Alfalfa', 'Allium (Onion)', 'Allspice', 'Almond', 'Alpine sweetvetch', 'Amaranth', 'American butterfish', 'American cranberry', 'American lobster', 'American pokeweed', 'American shad', 'Anatidae (Duck, Goose, Swan)', 'Anchovy', 'Angelica', 'Anguilliformes (Eel)', 'Animal foods', 'Anise', 'Annual wild rice', 'Antelope', 'Apple', 'Apple cider', 'Apricot', 'Arabica coffee', 'Arctic blackberry', 'Arctic ground squirrel', 'Arepa', 'Arrowhead', 'Arrowroot', 'Ascidians', 'Asian pear', 'Asparagus', 'Atlantic cod', 'Atlantic croaker', 'Atlantic halibut', 'Atlantic herring', 'Atlantic mackerel', 'Atlantic menhaden', 'Atlantic pollock', 'Atlantic salmon', 'Atlantic wolffish', 'Avocado', 'Babassu palm', 'Baby food', 'Bagel', 'Baked beans', 'Baked potato', 'Bamboo shoots', 'Banana', 'Barley', 'Bayberry', 'Bean', 'Bearded seal', 'Beaver', 'Beech nut', 'Beefalo', 'Beer', 'Beluga whale', 'Berry wine', 'Beverages', 'Bilberry', 'Biscuit', 'Bison', 'Bitter gourd', 'Bivalvia (Clam, Mussel, Oyster)', 'Black bear', 'Black cabbage', 'Black chokeberry', 'Black crowberry', 'Black elderberry', 'Black huckleberry', 'Black mulberry', 'Black radish', 'Black raspberry', 'Black salsify', 'Black walnut', 'Black-eyed pea', 'Blackcurrant', 'Blue crab', 'Blue mussel', 'Blue whiting', 'Bluefish', 'Bog bilberry', 'Borage', 'Bowhead whale', 'Boysenberry', 'Brassicas', 'Brazil nut', 'Breadfruit', 'Breadnut tree seed', 'Breakfast cereal', 'Breakfast sandwich', 'Broad bean', 'Broad whitefish', 'Broccoli', 'Brown bear', 'Brussel sprouts', 'Buffalo', 'Buffalo currant', 'Bulgur', 'Burbot', 'Burdock', 'Burrito', 'Butter', 'Butter substitute', 'Butterfat', 'Buttermilk', 'Butternut', 'Butternut squash', 'Cabbage', 'Cake', 'Calabash', 'Canada blueberry', 'Candy bar', 'Canola', 'Capers', 'Caraway', 'Cardamom', 'Cardoon', 'Caribou', 'Carob', 'Carp bream', 'Carrot', 'Cascade huckleberry', 'Casein', 'Cashew nut', 'Cassava', 'Catfish', 'Catjang pea', 'Cattle (Beef, Veal)', 'Cauliflower', 'Celeriac', 'Celery leaves', 'Celery stalks', 'Cereals and cereal products', 'Cetacea (Dolphin, Porpoise, Whale)', 'Ceylon cinnamon', 'Channel catfish', 'Chanterelle', 'Charr', 'Chayote', 'Cheese', 'Cherimoya', 'Cherry tomato', 'Chervil', 'Chestnut', 'Chewing gum', 'Chia', 'Chicken (Cock, Hen, Rooster)', 'Chickpea', 'Chicory', 'Chicory leaves', 'Chicory roots', 'Chili', 'Chimichanga', 'Chinese bayberry', 'Chinese broccoli', 'Chinese cabbage', 'Chinese chestnut', 'Chinese chives', 'Chinese cinnamon', 'Chinese mustard', 'Chinese water chestnut', 'Chinook salmon', 'Chives', 'Chocolate', 'Chocolate mousse', 'Chocolate spread', 'Chum salmon', 'Cichlidae (Tilapia)', 'Cinnamon', 'Cisco', 'Citrus', 'Clawed lobster', 'Climbing bean', 'Cloud ear fungus', 'Cloudberry', 'Cloves', 'Clupeinae (Herring, Sardine, Sprat)', 'Coalfish pollock', 'Cocktail', 'Cocoa and cocoa products', 'Cocoa bean', 'Cocoa butter', 'Cocoa liquor', 'Cocoa powder', 'Coconut', 'Coffee', 'Coffee and coffee products', 'Coffee mocha', 'Coffee substitute', 'Coho salmon', 'Cold cut', 'Colorado pinyon', 'Columbidae (Dove, Pigeon)', 'Common bean', 'Common beet', 'Common buckwheat', 'Common cabbage', 'Common carp', 'Common chokecherry', 'Common dab', 'Common grape', 'Common hazelnut', 'Common ling', 'Common mushroom', 'Common octopus', 'Common oregano', 'Common pea', 'Common persimmon', 'Common sage', 'Common salsify', 'Common thyme', 'Common verbena', 'Common walnut', 'Common wheat', 'Conch', 'Condensed milk', 'Cooking oil', 'Coriander', 'Corn', 'Corn chip', 'Corn grits', 'Corn salad', 'Cornbread', 'Cornmint', 'Cottonseed', 'Couscous', 'Cowpea', 'Crab', 'Cracker', 'Crayfish', 'Cream', 'Cream substitute', 'Crisp bread', 'Crustaceans', 'Cucumber', 'Cucurbita (Gourd)', 'Cumin', 'Cupuaçu', 'Curry powder', 'Cusk', 'Custard apple', 'Cuttlefish', 'Daikon radish', 'Dandelion', 'Date', 'Deer', 'Deerberry', 'Devilfish', 'Dill', 'Dock', 'Dolphin fish', 'Domestic goat', 'Domestic pig (Piglet, Pork)', 'Dough', 'Dragée', 'Dried milk', 'Dripping', 'Dulce de leche', 'Dumpling', 'Dungeness crab', 'Durian', 'Eastern oyster', 'Edible shell', 'Egg roll', 'Egg substitute', 'Eggplant', 'Eggs', 'Elderberry', 'Elk', "Elliott's blueberry", 'Empanada', 'Emu', 'Enchilada', 'Endive', 'Energy drink', 'Enokitake', 'Epazote', 'European anchovy', 'European chestnut', 'European cranberry', 'European plum', 'European rabbit', 'Evaporated milk', 'Evening primrose', 'Evergreen huckleberry', 'Falafel', 'Fats and oils', 'Feijoa', 'Fennel', 'Fenugreek', 'Fig', 'Fireweed', 'Fish burger', 'Fishes', 'Flatfish', 'Flaxseed', 'Florida pompano', 'Flour', 'Focaccia', 'Fortified wine', 'Fox grape', 'French plantain', 'French toast', 'Freshwater drum', 'Freshwater eel', 'Frozen yogurt', 'Fruit gum', 'Fruit juice', 'Fruit preserve', 'Fruit salad', 'Fruit-flavor drink', 'Fruits', 'Frybread', 'Fudge', 'Gadiformes (Cod, Hake)', 'Gadus (Common cod)', 'Garden cress', 'Garden onion', 'Garden onion (var.)', 'Garden rhubarb', 'Garden tomato', 'Garden tomato (var.)', 'Garfish', 'Garland chrysanthemum', 'Garlic', 'Gefilte fish', 'Gelatin', 'Gelatin dessert', 'German camomile', 'Giant butterbur', 'Gin', 'Ginger', 'Ginkgo nuts', 'Ginseng', 'Globe artichoke', 'Gooseberry', 'Gram bean', 'Grape', 'Grape wine', 'Grapefruit', 'Grapefruit/Pummelo hybrid', 'Grass pea', 'Great horned owl', 'Greater sturgeon', 'Green bean', 'Green bell pepper', 'Green turtle', 'Green vegetables', 'Green zucchini', 'Greenland halibut/turbot', 'Greenthread tea', 'Greylag goose', 'Groundcherry', 'Grouper', 'Guava', 'Guinea hen', 'Haddock', 'Half-highbush blueberry', 'Hamburger', 'Hard wheat', 'Hazelnut', 'Heart of palm', 'Hedge mustard', 'Herbs and Spices', 'Hibiscus tea', 'Hickory nut', 'Highbush blueberry', 'Hippoglossus (Common halibut)', 'Honey', 'Horchata', 'Horned melon', 'Horse', 'Horseradish', 'Horseradish tree', 'Hot chocolate', 'Hot dog', 'Hummus', 'Hushpuppy', 'Hyacinth bean', 'Hyssop', 'Ice cream', 'Ice cream cone', 'Icing', 'Irish moss', 'Italian oregano', 'Italian sweet red pepper', 'Jackfruit', 'Japanese chestnut', 'Japanese persimmon', 'Japanese pumpkin', 'Japanese walnut', 'Java plum', 'Jellyfish', 'Jerusalem artichoke', "Jew's ear", 'Jicama', 'Jostaberry', 'Jujube', 'Junket', 'Jute', 'Kai-lan', 'Kale', 'Kefir', 'Kelp', 'Ketchup', 'King mackerel', 'Kiwi', 'Kohlrabi', 'Komatsuna', 'Kombu', 'Kumquat', 'Lake trout', 'Lambsquarters', 'Lard', 'Lasagna', 'Leather chiton', 'Leavening agent', 'Leek', 'Lemon', 'Lemon balm', 'Lemon grass', 'Lemon sole', 'Lemon thyme', 'Lemon verbena', 'Lentils', 'Lettuce', 'Lichee', 'Lima bean', 'Lime', 'Linden', 'Lingcod', 'Lingonberry', 'Liquor', 'Liquorice', 'Loganberry', 'Longan', 'Loquat', 'Lotus', 'Lovage', 'Lowbush blueberry', 'Lumpsucker', 'Lupine', 'Macadamia nut', 'Macadamia nut (M. tetraphylla)', 'Macaroni and cheese', 'Madeira wine', 'Maitake', 'Malabar plum', 'Malabar spinach', 'Mallard duck', 'Malus (Crab apple)', 'Mamey sapote', 'Mammee apple', 'Mandarin orange (Clementine, Tangerine)', 'Mango', 'Margarine', 'Margarine-like spread', 'Marine mussel', 'Marshmallow', 'Marzipan', 'Meat bouillon', 'Meatball', 'Meatloaf', 'Medlar', 'Mentha (Mint)', 'Meringue', 'Mexican groundcherry', 'Mexican oregano', 'Milk (Cow)', 'Milk (Human)', 'Milk (Other mammals)', 'Milk and milk products', 'Milk substitute', 'Milkfish', 'Milkshake', 'Millet', 'Miso', 'Mixed nuts', 'Molasses', 'Mollusks', 'Monkfish', 'Moose', 'Morchella (Morel)', 'Moth bean', 'Mountain hare', 'Mountain yam', 'Mugwort', 'Mulberry', 'Mule deer', 'Multigrain bread', 'Mung bean', 'Muscadine grape', 'Mushrooms', 'Muskmelon', 'Muskrat', 'Mustard', 'Mustard spinach', 'Nachos', 'Nance', 'Nanking cherry', 'Napa cabbage', 'Naranjilla', 'Narrowleaf cattail', 'Natal plum', 'Natto', 'Nectarine', 'New Zealand spinach', 'Nopal', 'North Pacific giant octopus', 'Northern bluefin tuna', 'Northern pike', 'Norway haddock', 'Norway lobster', 'Norway pout', 'Nougat', 'Nutmeg', 'Nutritional drink', 'Nuts', 'Nuttall cockle', 'Oat', 'Oat bread', 'Ocean pout', 'Ohelo berry', 'Oil palm', 'Oil-seed Camellia', 'Okra', 'Olive', 'Onion-family vegetables', 'Opium poppy', 'Opossum', 'Orange bell pepper', 'Orange mint', 'Orange roughy', 'Oregon yampah', 'Oriental wheat', 'Ostrich', 'Ostrich fern', 'Other alcoholic beverage', 'Other animal fat', 'Other beverage', 'Other bread', 'Other bread product', 'Other candy', 'Other cereal product', 'Other cocoa product', 'Other dish', 'Other fermented milk', 'Other fish product', 'Other frozen dessert', 'Other fruit product', 'Other meat product', 'Other pasta dish', 'Other sandwich', 'Other snack food', 'Other soy product', 'Other vegetable product', 'Other wine', 'Oval-leaf huckleberry', 'Oxheart cabbage', 'Oyster mushroom', 'Pacific cod', 'Pacific halibut', 'Pacific herring', 'Pacific jack mackerel', 'Pacific ocean perch', 'Pacific oyster', 'Pacific rockfish', 'Pacific salmon', 'Pacific sardine', 'Painted comber', 'Pak choy', 'Pan dulce', 'Pancake', 'Papaya', 'Parsley', 'Parsnip', 'Passion fruit', 'Pasta', 'Pastry', 'Pate', 'Peach', 'Peach (var.)', 'Peanut', 'Pear', 'Pecan nut', 'Pectin', 'Pepper (C. annuum)', 'Pepper (C. baccatum)', 'Pepper (C. chinense)', 'Pepper (C. frutescens)', 'Pepper (C. pubescens)', 'Pepper (Capsicum)', 'Pepper (Spice)', 'Peppermint', 'Perciformes (Perch-like fishes)', 'Percoidei (Bass and others)', 'Persian lime', 'Persimmon', 'Pheasant', 'Phyllo dough', 'Pie', 'Pie crust', 'Pie filling', 'Pigeon pea', 'Pikeperch', 'Piki bread', 'Pili nut', 'Pine nut', 'Pineapple', 'Pineappple sage', 'Pink salmon', 'Pistachio', 'Pita bread', 'Pitanga', 'Pizza', 'Plains prickly pear', 'Pleuronectidae (Dab, Halibut, Plaice)', 'Polar bear', 'Pollock', 'Pomegranate', 'Pomes', 'Popcorn', 'Poppy', 'Port wine', 'Pot marjoram', 'Pot pie', 'Potato', 'Potato bread', 'Potato chip', 'Potato gratin', 'Potato puffs', 'Prairie turnip', 'Prickly pear', 'Processed cheese', 'Prunus (Cherry, Plum)', 'Pudding', 'Pulses', 'Pummelo', 'Pumpkinseed sunfish', 'Pupusa', 'Purple laver', 'Purple mangosteen', 'Purslane', 'Quail', 'Quesadilla', 'Quince', 'Quinoa', 'Rabbit', 'Raccoon', 'Radish', 'Radish (var.)', 'Rainbow smelt', 'Rainbow trout', 'Raisin bread', 'Rambutan', 'Rape', 'Rapini', 'Ravioli', 'Red algae', 'Red beetroot', 'Red bell pepper', 'Red huckleberry', 'Red king crab', 'Red raspberry', 'Red rice', 'Redcurrant', 'Relish', 'Remoulade', 'Rice', 'Rice bread', 'Rice cake', 'Ringed seal', 'Robusta coffee', 'Rock ptarmigan', 'Rocket salad', 'Rocket salad (ssp.)', 'Roe', 'Romaine lettuce', 'Roman camomile', 'Root vegetables', 'Rose hip', 'Roselle', 'Rosemary', 'Rowal', 'Rowanberry', 'Rubus (Blackberry, Raspberry)', 'Rum', 'Rye', 'Rye bread', 'Sablefish', 'Sacred lotus', 'Safflower', 'Saffron', 'Sago palm', 'Sake', 'Salad', 'Salad dressing', 'Salmonberry', 'Salmonidae (Salmon, Trout)', 'Salt', 'Sapodilla', 'Saskatoon berry', 'Sauce', 'Sausage', 'Savoy cabbage', 'Scallop', 'Scarlet bean', 'Scombridae (Bonito, Mackerel, Tuna)', 'Scrapple', 'Scup', 'Sea cucumber', 'Sea-buckthornberry', 'Seatrout', 'Semolina', 'Sesame', 'Sesbania flower', 'Shallot', 'Shark', 'Shea tree', 'Sheefish', 'Sheep (Mutton, Lamb)', 'Sheepshead', 'Sherry', 'Shiitake', 'Shortening', 'Shrimp', 'Silver linden', 'Skipjack tuna', 'Skunk currant', 'Small-leaf linden', 'Smelt', 'Snack bar', 'Snail', 'Snapper', 'Snow crab', 'Sockeye salmon', 'Soft drink', 'Soft-necked garlic', 'Sorghum', 'Sorrel', 'Soup', 'Sour cherry', 'Sourdock', 'Sourdough', 'Soursop', 'Soy bean', 'Soy cream', 'Soy milk', 'Soy sauce', 'Soy yogurt', 'Spanish mackerel', 'Sparkleberry', 'Spearmint', 'Spelt', 'Spinach', 'Spiny dogfish', 'Spiny lobster', 'Spirit', 'Spirulina', 'Spot croaker', 'Spotted seal', 'Spread', 'Squab', 'Squashberry', 'Squid', 'Squirrel', 'Star anise', 'Star fruit', 'Steller sea lion', 'Stew', 'Strawberry', 'Strawberry guava', 'Striped bass', 'Striped mullet', 'Stuffing', 'Sturgeon', 'Succotash', 'Sugar', 'Sugar apple', 'Sugar substitute', 'Summer grape', 'Summer savory', 'Sunburst squash (pattypan squash)', 'Sunflower', 'Swamp cabbage', 'Swede', 'Sweet basil', 'Sweet bay', 'Sweet cherry', 'Sweet custard', 'Sweet marjoram', 'Sweet orange', 'Sweet potato', 'Sweet rowanberry', 'Swiss chard', 'Swordfish', 'Syrup', 'Taco', 'Tallow', 'Tamale', 'Tamarind', 'Tapioca pearl', 'Taro', 'Tarragon', 'Tartary buckwheat', 'Tea', 'Tea leaf willow', 'Teff', 'Thistle', 'Thunnus (Common tuna)', 'Tilefish', 'Tinda', 'Toffee', 'Tofu', 'Topping', 'Tortilla', 'Tortilla chip', 'Tostada', 'Towel gourd', 'Trail mix', 'Tree fern', 'Triticale', 'Tronchuda cabbage', 'True frog', 'True oyster', 'True seal', 'True sole', 'Tunicate', 'Turbot', 'Turkey', 'Turmeric', 'Turnip', 'Ucuhuba', 'Unclassified food or beverage', 'Vaccinium (Blueberry, Cranberry, Huckleberry)', 'Vanilla', 'Vegetable juice', 'Vegetarian food', 'Veggie burger', 'Velvet duck', 'Vermouth', 'Vinegar', 'Vodka', 'Waffle', 'Wakame', 'Walleye', 'Walnut', 'Walrus', 'Wasabi', 'Water', 'Watercress', 'Watermelon', 'Wax apple', 'Wax gourd', 'Welsh onion', 'Wheat', 'Wheat bread', 'Whelk', 'Whey', 'Whisky', 'White cabbage', 'White lupine', 'White mustard', 'White sucker', 'Whitefish', 'Whiting', 'Wild boar', 'Wild carrot', 'Wild celery', 'Wild leek', 'Wild rice', 'Winged bean', 'Winter savory', 'Winter squash', 'Wonton wrapper', 'Yam', 'Yardlong bean', 'Yautia', 'Yellow bell pepper', 'Yellow pond-lily', 'Yellow wax bean', 'Yellow zucchini', 'Yellowfin tuna', 'Yellowtail amberjack', 'Ymer', 'Yogurt', 'Zwieback', 'dumplings', 'milk', 'muesli']

In [ ]:
print()